### PR TITLE
check if sessionid exists, before setting it as a cookie

### PR DESCRIPTION
**Pull request by roerch**

### CODE REVIEW

**Comment by jochenklar** [comment]
Makes sense, but can you give a short explanation why this is a problem?

**Comment by roerch** [comment]
If no user is logged in, then an error message complaining about the non-existing sessionid, is written within the Wordpress content on the website.

**Comment by jochenklar** [comment]
On the webpage or in the error log? I cannot anything here: https://gaia.aip.de/cms/documentation/

**Comment by roerch** [comment]
On the website itself. Attached a screenshot from my development environment.
sessionid

**Comment by jochenklar** [comment]
Maybe its because you have some strict flag enabled. But I don't think we need to worry about the AIP pages.

**Pull request merged**
